In [184]:
import pandas as pd
import numpy as np
import time
import sklearn
import pymysql
from sqlalchemy import create_engine
from pyecharts.charts import Bar3D

In [144]:
sheet_names = ['2015','2016','2017','2018']
sale_data = pd.read_excel('./RFMsales.xlsx',sheet_name=sheet_names) # 读取为字典，每一张表为一个字段
sale_data

{'2015':               会员ID         订单号       提交日期    订单金额
 0      15278002468  3000304681 2015-01-01   499.0
 1      39236378972  3000305791 2015-01-01  2588.0
 2      38722039578  3000641787 2015-01-01   498.0
 3      11049640063  3000798913 2015-01-01  1572.0
 4      35038752292  3000821546 2015-01-01    10.1
 ...            ...         ...        ...     ...
 30769  39368100847  4281994827 2015-12-31   828.0
 30770       409757  4282010457 2015-12-31   199.0
 30771  38380526114  4282017675 2015-12-31   208.0
 30772     28074988  4282019440 2015-12-31    89.0
 30773  39460363230  4282025309 2015-12-31   719.0

 [30774 rows x 4 columns],
 '2016':               会员ID         订单号       提交日期     订单金额
 0      39288120141  4282025766 2016-01-01    76.00
 1      39293812118  4282037929 2016-01-01  7599.00
 2      27596340905  4282038740 2016-01-01   802.00
 3      15111475509  4282043819 2016-01-01    65.00
 4      38896594001  4282051044 2016-01-01    95.00
 ...            ...         ...        ...      ...
 41273  35336052906  4324910145 2016-12-31    99.00
 41274  39305835721  4324910148 2016-12-31   238.89
 41275  39296945352  4324910770 2016-12-31   765.00
 41276  14791026234  4324911025 2016-12-31    45.80
 41277  16779755770  4324911048 2016-12-31   119.00

 [41278 rows x 4 columns],
 '2017':               会员ID         订单号       提交日期    订单金额
 0      38765290840  4324911135 2017-01-01  1799.0
 1      39305832102  4324911213 2017-01-01   369.0
 2      34190994969  4324911251 2017-01-01   189.0
 3      38986333210  4324911283 2017-01-01   169.0
 4          4271359  4324911355 2017-01-01    78.0
 ...            ...         ...        ...     ...
 50834  39155833075  4338762307 2017-12-31    96.0
 50835  29523124076  4338762514 2017-12-31    99.0
 50836      7807573  4338762906 2017-12-31   258.0
 50837  36642530033  4338762958 2017-12-31   286.0
 50838  39155901156  4338763879 2017-12-31   249.0

 [50839 rows x 4 columns],
 '2018':               会员ID         订单号       提交日期    订单金额
 0      39229691808  4338764262 2018-01-01  3646.0
 1      39293668916  4338764363 2018-01-01  3999.0
 2      35059646224  4338764376 2018-01-01    10.1
 3          1084397  4338770013 2018-01-01   828.0
 4          3349915  4338770121 2018-01-01  3758.0
 ...            ...         ...        ...     ...
 81344  39229485704  4354225182 2018-12-31   249.0
 81345  39229021075  4354225188 2018-12-31    89.0
 81346  39288976750  4354230034 2018-12-31    48.5
 81347     26772630  4354230163 2018-12-31  3196.0
 81348  39455580335  4354235084 2018-12-31  2999.0

 [81349 rows x 4 columns]}

In [145]:
for year in sheet_names:
    sale_data[year] = sale_data[year].query('订单金额 > 1')
    sale_data[year].dropna(inplace=True)
    sale_data[year]['max_year'] = sale_data[year]['提交日期'].max()
    print(sale_data[year].info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30574 entries, 0 to 30773
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   会员ID      30574 non-null  int64
 1   订单号       30574 non-null  int64
 2   提交日期      30574 non-null  datetime64[ns]
 3   订单金额      30574 non-null  float64
 4   max_year  30574 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2)
memory usage: 1.4 MB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 41001 entries, 0 to 41277
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   会员ID      41001 non-null  int64
 1   订单号       41001 non-null  int64
 2   提交日期      41001 non-null  datetime64[ns]
 3   订单金额      41001 non-null  float64
 4   max_year  41001 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2)
memory usage: 1.9 MB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 50451 entries, 0 to 50838
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   会员ID      50451 non-null  int64
 1   订单号       50451 non-null  int64
 2   提交日期      50451 non-null  datetime64[ns]
 3   订单金额      50451 non-null  float64
 4   max_year  50451 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2)
memory usage: 2.3 MB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 80801 entries, 0 to 81348
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   会员ID      80801 non-null  int64
 1   订单号       80801 non-null  int64
 2   提交日期      80801 non-null  datetime64[ns]
 3   订单金额      80801 non-null  float64
 4   max_year  80801 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2)
memory usage: 3.7 MB
None

In [156]:
merged_data = pd.concat(list(sale_data.values())[:4],axis=0,ignore_index=True)
merged_data['year'] = merged_data['max_year'].dt.year #  datetime 类型的列可以通过 .dt 访问器来获取和操作这些日期和时间信息
merged_data['date_interval'] = (merged_data['max_year'] - merged_data['提交日期']).dt.days
merged_data

,会员ID,订单号,提交日期,订单金额,max_year,year,date_interval
0,15278002468,3000304681,2015-01-01,499.0,2015-12-31,2015,364
1,39236378972,3000305791,2015-01-01,2588.0,2015-12-31,2015,364
2,38722039578,3000641787,2015-01-01,498.0,2015-12-31,2015,364
3,11049640063,3000798913,2015-01-01,1572.0,2015-12-31,2015,364
4,35038752292,3000821546,2015-01-01,10.1,2015-12-31,2015,364
...,...,...,...,...,...,...,...
202822,39229485704,4354225182,2018-12-31,249.0,2018-12-31,2018,0
202823,39229021075,4354225188,2018-12-31,89.0,2018-12-31,2018,0
202824,39288976750,4354230034,2018-12-31,48.5,2018-12-31,2018,0
202825,26772630,4354230163,2018-12-31,3196.0,2018-12-31,2018,0
202826,39455580335,4354235084,2018-12-31,2999.0,2018-12-31,2018,0

In [147]:
RMF_data = merged_data.groupby(['year','会员ID'],as_index=False).agg({
    '订单号':"count",
    "date_interval":'min',
    '订单金额':'sum'
}).rename(columns={'year':'year','会员ID':'ID','date_interval':'r','订单号':'f','订单金额':'m'})
RMF_data

        year           ID  f    r       m
0       2015          267  2  197   105.0
1       2015          282  1  251    29.7
2       2015          283  1  340  5398.0
3       2015          343  1  300   118.0
4       2015          525  3   37   213.0
...      ...          ... ..  ...     ...
148586  2018  39538034299  1  272    49.0
148587  2018  39538034662  1  189  3558.0
148588  2018  39538035729  1  179  3699.0
148589  2018  39545237824  1  275    49.0
148590  2018  39546136285  1  163    19.9

[148591 rows x 5 columns]

In [161]:
# 定义三分法边界
# 定义区间
des = RMF_data[['r','m','f']].describe().T
print(des)
r_bins = [-1,79,255,365]
m_bins = [1, 69.0, 1199.0, 206251.8]
f_bins = [0,2,5,130]

# 使用cut划分,自动划分区间
# pd.cut(RMF_data['r'],bins=3).unique()

# 给定区间划分，每个数值分配到一个区间,区间使用labels进行命名（评分）
# pd.cut(RMF_data['r'],bins=r_bins,labels=[3,2,1]).unique()
RMF_data['r_label'] = pd.cut(RMF_data['r'],bins=r_bins,labels=[3,2,1]).astype(str)  #bins 定义的区间是按照从小到大的顺序排列的
RMF_data['f_label'] = pd.cut(RMF_data['f'],bins=f_bins,labels=[1,2,3]).astype(str)
RMF_data['m_label'] = pd.cut(RMF_data['m'],bins=m_bins,labels=[1,2,3]).astype(str)
RMF_data.set_index(['ID','year'],inplace=True)

      count         mean          std  min   25%    50%     75%       max
r  148591.0   165.524043   101.988472  0.0  79.0  156.0   255.0     365.0
m  148591.0  1323.741329  3753.906883  1.5  69.0  189.0  1199.0  206251.8
f  148591.0     1.365002     2.626953  1.0   1.0    1.0     1.0     130.0

KeyError: "None of ['ID', 'year'] are in the columns"

In [177]:
# 直接拼接
RMF_data['RFM_group'] = RMF_data['r_label'] + RMF_data['f_label'] + RMF_data['m_label']
# 加权计算
RMF_data['RFM_group'] = 0.2 * (RMF_data['r_label']).astype(int) + 0.3 * (RMF_data['f_label']).astype(int) + 0.5 * (RMF_data['m_label']).astype(int)
# RMF_data.loc[RMF_data['RFM_group']==3,'RFM_group']
RMF_data

                  f    r       m r_label f_label m_label  RFM_group
ID          year
267         2015  2  197   105.0       2       1       2        1.7
282         2015  1  251    29.7       2       1       1        1.2
283         2015  1  340  5398.0       1       1       3        2.0
343         2015  1  300   118.0       1       1       2        1.5
525         2015  3   37   213.0       3       2       2        2.2
...              ..  ...     ...     ...     ...     ...        ...
39538034299 2018  1  272    49.0       1       1       1        1.0
39538034662 2018  1  189  3558.0       2       1       3        2.2
39538035729 2018  1  179  3699.0       2       1       3        2.2
39545237824 2018  1  275    49.0       1       1       1        1.0
39546136285 2018  1  163    19.9       2       1       1        1.2

[148591 rows x 7 columns]

In [191]:
# 保存到MYSQL
# 创建引擎对象
engine = create_engine('mysql+pymysql://root:123456@localhost:3306/rfm_db?charset=utf8')
RMF_data.to_sql('rfm_score',engine)

148591

In [193]:
pd.read_sql('select * from rfm_score limit 100',engine)

       ID  year  f    r       m r_label f_label m_label  RFM_group
0     267  2015  2  197   105.0       2       1       2        1.7
1     282  2015  1  251    29.7       2       1       1        1.2
2     283  2015  1  340  5398.0       1       1       3        2.0
3     343  2015  1  300   118.0       1       1       2        1.5
4     525  2015  3   37   213.0       3       2       2        2.2
..    ...   ... ..  ...     ...     ...     ...     ...        ...
95  40554  2015  1  131    69.9       2       1       2        1.7
96  40747  2015  1  216   110.0       2       1       2        1.7
97  41688  2015  1  277    10.1       1       1       1        1.0
98  41917  2015  3  232    10.0       2       2       1        1.5
99  42625  2015  1  300    95.0       1       1       2        1.5

[100 rows x 9 columns]